name: GitHub Actions workflow with push to GHCR.io and DockerHub

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      
jobs:
  build-push-images:
    name: Build and push to GHCR
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1
        

      - name: Login to GitHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          file: ./Dockerfile
          push: true
          tags: |
            97060/zadanie1:multiplatform
            ghcr.io/97060/zadanie1:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      
